In [25]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列Aと行列Bの内積を計算
result = np.dot(A, B)

# 最大値を求める
max_value = np.max(result)

print("行列Aと行列Bの内積:")
print(result)
print("最大値:", max_value)



行列Aと行列Bの内積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
